### ISSUE TITLE
多线程运行报错

### ISSUE THREAD

**Issue by Bill-Haku** [tencent-connect/botpy#115]
尝试将主要的Client类放到子线程中运行时，程序报错：

```
  File "/Users/hakubill/PycharmProjects/qqpixivbot/main.py", line 200, in start_general_event_handler
    client = AyakiClient(intents=intents)
  File "/Users/hakubill/PycharmProjects/qqpixivbot/venv/lib/python3.9/site-packages/botpy/client.py", line 56, in __init__
    self.loop: asyncio.AbstractEventLoop = asyncio.get_event_loop()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'general_thread'.
```

（不知道这个[StackOverflow上的讨论](https://stackoverflow.com/questions/46727787/runtimeerror-there-is-no-current-event-loop-in-thread-in-async-apscheduler)是否有用）

**Comment by yinlinghunjiang** [comment]
please create a new async loop like 
```
client= asyncio.new_event_loop()
asyncio.set_event_loop(client)
```

**Comment by Bill-Haku** [comment]
> 是否已解决, 请问运用场景是?

@ReadSmall 我想开两个线程分别处理at的被动回复和在每天的固定时间主动发送消息。但是将Client类放到子线程运行时会报错。目前暂时把它留在主线程，可以实现功能。

**Comment by ReadSmall** [comment]
可单独调用api来实现外部发送消息的







---Original---
From: ***@***.***&gt;
Date: Sat, Jul 16, 2022 17:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tencent-connect/botpy] 多线程运行报错 (Issue #115)




  
是否已解决, 请问运用场景是?
  
@ReadSmall 我想开两个线程分别处理at的被动回复和在每天的固定时间主动发送消息。但是将Client类放到子线程运行时会报错。目前暂时把它留在主线程，可以实现功能。

**Comment by Bill-Haku** [comment]
> 可单独调用api来实现外部发送消息的

我现在还用的是原来的`qqbot`里的api，还可以暂时用。

**Comment by ReadSmall** [comment]
可以试试这个demo

![image](https://user-images.githubusercontent.com/48905684/180184296-04fb53f8-7a0a-4d28-9151-332952b3c39b.png)


```python 
async def reset_guild_log():
    http = BotHttp(timeout=5, app_id=conf_data["token"]["appid"], token=conf_data["token"]["token"])
    api = botpy.BotAPI(http)
    await api.post_message(channel_id=conf_data["params"]["date_channel"], content="test")
    await http.close()
    return
```

**Comment by Bill-Haku** [comment]
好的，感谢协助。
