### ISSUE TITLE
每日主动推送消息出错

### ISSUE THREAD

**Issue by UncommonRuler** [tencent-connect/botpy#125]
我使用apscheduler模块执行定时任务，统计机器人一天的使用情况，但是 api.post_dms 发送消息总是失败，请看看我的代码问题出在哪里？
![image](https://user-images.githubusercontent.com/21164383/219757538-25211f2b-6a89-468e-9482-652ec700b949.png)
![image](https://user-images.githubusercontent.com/21164383/219757631-1a2cc426-035d-49f4-a0dd-6e2243ffbe03.png)
日志：
![image](https://user-images.githubusercontent.com/21164383/219758046-717444c5-ba7f-4578-b79d-f1559732b33f.png)
不是很了解"push time out of range"是什么问题，希望能得到各位的帮助。

**Comment by traveler-vee** [comment]
是晚上发的消息吗？晚上有一段时间api是不允许发送主动消息的，可以查询错误码

https://bot.q.qq.com/wiki/develop/api/openapi/error/error.html#%E9%94%99%E8%AF%AF%E7%A0%81%E5%A4%84%E7%90%86

304022 | PUSH_TIME 推送消息时间限制




304022 | PUSH_TIME 推送消息时间限制
-- | --

**Comment by UncommonRuler** [comment]
谢谢，解决了。文档里说一下时间范围的问题吧，之前一直在考虑是不是超时。

**Comment by blyc** [comment]
> 是晚上发的消息吗？晚上有一段时间api是不允许发送主动消息的，可以查询错误码 @UncommonRuler
> 
> https://bot.q.qq.com/wiki/develop/api/openapi/error/error.html#%E9%94%99%E8%AF%AF%E7%A0%81%E5%A4%84%E7%90%86
> 
> 304022 | PUSH_TIME 推送消息时间限制
> 
> 304022	PUSH_TIME 推送消息时间限制

请问有具体的时间范围吗？
