### ISSUE TITLE
求botpy版的定时主动发帖/消息的例子

### ISSUE THREAD

**Issue by eastlovsky** [tencent-connect/botpy#134]
看了半天没弄明白，主动发消息或者帖子，用Botpy怎么实现的？

**Comment by traveler-vee** [comment]
> 看了半天没弄明白，主动发消息或者帖子，用Botpy怎么实现的？

https://github.com/tencent-connect/bot-onduty/blob/master/flow/schedule.py
可以参考值班机器人这个定时主动发消息的例子
