### ISSUE TITLE
我想知道markdown和ark以及其他消息类型的权限应该怎么获取

### ISSUE THREAD

**Issue by dongmingzjj** [tencent-connect/botpy#140]
在文档里翻遍了找不到申请的地方

**Comment by traveler-vee** [comment]
需要找运营同学专门申请哦

**Comment by liaoyanglay** [comment]
加入频道联系运营同学申请
![0405d368ef355de52147857e1b548831_720](https://github.com/tencent-connect/botpy/assets/31206068/53ddf419-b361-4b13-b1b2-89881049c6c7)
