### ISSUE TITLE
发送消息内容中包含1.sh时出现403

### ISSUE THREAD

**Issue by YuXiaohuann** [tencent-connect/botpy#144]
代码如下：
`await self.api.post_message(channel_id=message.channel_id,
                                    content="1.sh")`
错误信息：
错误代码: 403, 返回内容: {'code': 304003, 'message': 'url not allowed'}

应该是为了防止命令注入 被拦截了
有什么办法将消息中的`.`转义吗

**Comment by feilongproject** [comment]
因为腾讯把`1.sh`判断成url了，而没有在后台报备的url无法发送，一种解决办法就是把`.`变成`。`
