### ISSUE TITLE
请求发行同步风格的SDK

### ISSUE THREAD

**Issue by RockChinQ** [tencent-connect/botpy#152]
Python异步具有传染性，使用异步的botpy框架构建具有一定规模的同步程序非常麻烦，已有的同步程序适配异步的botpy框架同样难以完成。同时，新生入门学习和编写的多为同步风格的代码，强行要求使用异步，不便于推广。故请求发行同步版本SDK。

**Comment by cuckoo711** [comment]
bot框架的事件本身就是基于异步调控的，QQ机器人从登录开始就与服务器持续进行数据交互，如果用同步方式将会大大阻塞程序，且此业务并不适用于新手进行拓展开发
你可以试着将异步再进行一次封装使其可以在单一线程中使用，以此来实现伪同步风格

**Comment by liaoyanglay** [comment]
暂无计划
