### ISSUE TITLE
同一个报错会抛出两次

### ISSUE THREAD

**Issue by MomokkoW** [tencent-connect/botpy#17]
例如这样的报错
![](https://user-images.githubusercontent.com/78632509/150678085-428d315c-63b1-4e5b-93f4-e984e0308574.png)
就被qqbot和websocket两个模块同时抛出
在使用像Sentry这样的bug跟踪工具时会显示多个问题 不便管理
![](https://user-images.githubusercontent.com/78632509/150678145-ddaa461b-c7b2-4d4e-b51c-2beb4a926e8b.png)

**Comment by hwygithub** [comment]
#21 已经修复该问题
