### ISSUE TITLE
数据类型错误

### ISSUE THREAD

**Issue by cyx200902** [tencent-connect/botpy#173]
https://github.com/tencent-connect/botpy/blob/b409111e7c5f1078cfdc6be54fe7ae8f850c775d/botpy/api.py#L1390
函数post_group_message中msg_seq数据类型出错
应为int，sdk中为str
` msg_seq: str = 1, `

**Comment by liaoyanglay** [comment]
已修复

**Comment by cyx200902** [comment]
请检查，新版本的数据格式又错了https://github.com/tencent-connect/botpy/blob/master/botpy/api.py#L1436
