### ISSUE TITLE
Q群机器人发送图片的接口是哪个

### ISSUE THREAD

**Issue by Suz1e** [tencent-connect/botpy#182]
有没有示例？
用富媒体测试了github项目里的文件，但是错误代码500 不知道啥问题
[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/v2/groups/40DD9EC65EF74FA2A6E8AC55D3A520A0/files, 错误代码: 500, 返回内容: {'message': 'call inner proxy error',

还有没有其他的方式发送本地图片

**Comment by Suz1e** [comment]
只能富媒体 错误代码不知道咋回事 但解决了

**Comment by tusik** [comment]
你好，我想问问你使用下来post_group_file是不是这个接口只能使用网络url来让腾讯服务器从url下载图片，而不是直接从本地上传文件到服务器

**Comment by Suz1e** [comment]
> 你好，我想问问你使用下来post_group_file是不是这个接口只能使用网络url来让腾讯服务器从url下载图片，而不是直接从本地上传文件到服务器

是的，QQ群bot只能走url且443或80端口，暂未开放本地上传，但频道BOT可以，当然好像也有其他方法实现本地上传，不过我不会

**Comment by Suz1e** [comment]
> 同问

对 只能url
