### ISSUE TITLE
qq群发送图片不支持本地文件？

### ISSUE THREAD

**Issue by tusik** [tencent-connect/botpy#192]
频道可以直接使用本地文件url发送图片。
但是qq群里要先用post_group_file上传图片，但是url填写本地文件路径提示
```
    raise ServerError(message) from None  # adding from None to prevent chain exception being raised
botpy.errors.ServerError: 请求参数url无效
```

使用网络图片url的话可以发送成功。也就是说必须使用一个在线url才能发送图片？

**Comment by jdnjk** [comment]
官方不咋看这里

**Comment by liangmiQwQ** [comment]
有解决方案了吗

**Comment by tusik** [comment]
> 有解决方案了吗

没有，go的sdk里好像可以传base64的图片数据，但我看了python的没有。
所以我就直接图片存目录里，然后给目录加上域名访问。

**Comment by Suz1e** [comment]
BOT增加了Q群的本地上传图片功能，但是文档还没更新，pythonsdk可能也没更新
