### ISSUE TITLE
【BUG？】[ERROR] (robot.py:64)update_access_token获取token失败 RuntimeError: {'code': 100002, 'message': 'internal err'}

### ISSUE THREAD

**Issue by aJarOfCode** [tencent-connect/botpy#197]
我反复检查了好几遍，我的AppID和secret完全正确
完整报错信息：
RuntimeError: {'code': 100002, 'message': 'internal err'}

我查看了robot.py，似乎每次请求都会向https://bots.qq.com/app/getAppAccessToken 获取access_token，如果请求超时，捕获asyncio.TimeoutError异常，并打印超时信息。如果响应数据中没有access_token或expires_in字段，打印错误信息并抛出RuntimeError异常。显然我遇到了第二种情况。当成功之后才会返回机器人的token。我目前还没找出解决办法。

**Comment by 17794** [comment]
怎么解决的呀，我也遇到了同样的问题

**Comment by fexcode** [comment]
同问
