### ISSUE TITLE
无法监听消息事件

### ISSUE THREAD

**Issue by coolf** [tencent-connect/botpy#27]
![image](https://user-images.githubusercontent.com/31461422/156506195-3fc4cda2-d887-4830-bd5b-0721ef24c043.png)

```
qqbot.HandlerType.MESSAGE_EVENT_HANDLER
```

**Comment by coolf** [comment]
[用这个例子也同样的报错](https://github.com/tencent-connect/botpy/blob/master/examples/demo_announce.py)
是申请的频道问题么

**Comment by hwygithub** [comment]
4014是使用了没有授权的事件，如果是message事件是需要私域才能监听，at_message不需要私域和权限

**Comment by hwygithub** [comment]
> [用这个例子也同样的报错](https://github.com/tencent-connect/botpy/blob/master/examples/demo_announce.py) 是申请的频道问题么

这个例子需要私域权限，我们修改下为公域案例

**Comment by hwygithub** [comment]
已修改example
