### ISSUE TITLE
qqbot.Reaction 类（也就是WsEvent.EventMessageReactionAdd 事件的payload）能否在其target内新增一个消息发送者的key？

### ISSUE THREAD

**Issue by NessajCN** [tencent-connect/botpy#55]
目前 qqbot.Reaction 类
```python
class Reaction:
    def __init__(self, data=None):
        self.user_id: str = ""
        self.guild_id: str = ""
        self.channel_id: str = ""
        self.target: ReactionTarget = ReactionTarget()
        self.emoji: Emoji = Emoji()
        if data:
            self.__dict__ = data

class ReactionTarget:
    def __init__(self, data=None):
        self.id: str = ""
        self.type: int = 0
        if data:
            self.__dict__ = data
```
下只有 user_id，也就是表情发送者的id
Reaction.target: ReactioinTarget 只有id和type两个键名，也就是表情所回复的消息id和消息类型
如果我需要知道该消息id 是谁发的就必须调用 qqbot.MessageAPI.get_message(channel_id, message_id) 方法
```python
class MessageAPI(APIBase):
    def get_messages(self, channel_id: str, pager: MessagesPager) -> List[Message]:
        """
        获取指定消息列表

        :param channel_id: 频道ID
        :param pager: MessagesPager对象
        :return: Message 对象
        """
        url = get_url(APIConstant.messagesURI, self.is_sandbox).format(
            channel_id=channel_id
        )
        query = {}
        if pager.limit != "":
            query["limit"] = pager.limit

        if pager.type != "" and pager.id != "":
            query[pager.type] = pager.id

        response = self.http.get(url, params=query)
        return json.loads(response.content, object_hook=Message)
```
才能从返回值中（qqbot.Message）获取消息创建者 id，很不方便。
请问能否在qqbot.ReactionTarget类中添加 self.author 这样一个键名？

另外，使用上述 qqbot.MessageAPI.get_message(channel_id, message_id)  方法获取到的 message，
其 message.author.id 跟 监听 WsEvent.EventMessageCreate 事件收到的 payload 的 message.author.id 并不相同。
但是用f"<@!{message.author.id}>"返回出来的都是正确的用户，请问这两种id有何不同？能够互相查询吗？

**Comment by NessajCN** [comment]
> 针对ReactionTarget的问题，目前这个类的构造数据都是从后台的WsEvent里取的，需要等后台API提供 author 的信息，我们再加上。这一点可以在开发者频道里提一个建议到“问答|| API 接口“板块。
> 两种id只是后台存储时表示不一样，使用起来都是可以定位到正确的用户的
> 

请问这两种不同id能否方便地互相查询或转化？我目前做的机器人需要统计频道里用户获得的点赞数，两种id混用会导致无法正确计数。

**Comment by DaiJiChen** [comment]
> > 针对ReactionTarget的问题，目前这个类的构造数据都是从后台的WsEvent里取的，需要等后台API提供 author 的信息，我们再加上。这一点可以在开发者频道里提一个建议到“问答|| API 接口“板块。
> > 两种id只是后台存储时表示不一样，使用起来都是可以定位到正确的用户的
> 
> 请问这两种不同id能否方便地互相查询或转化？我目前做的机器人需要统计频道里用户获得的点赞数，两种id混用会导致无法正确计数。

据我所知，目前后台还没有提供接口可以实现两种id的互相转化。
