### ISSUE TITLE
日志能不能分天保存？

### ISSUE THREAD

**Issue by moian98** [tencent-connect/botpy#57]
我比较菜，只能用现成的SDK，不会自己调整
目前日志保存是在同一个log文件中，很不方便，数据多了使得整个日志文件很大。
能不能修改成按日期保存呢？

**Comment by traveler-vee** [comment]
请问使用的是哪个版本呢？

**Comment by moian98** [comment]
> 请使用哪个版本呢？

用的0.79+啊，前几天更库新后我clong了，应该是未发版的0.80吧？

**Comment by moian98** [comment]
> 我使用的已经每天传送前一天的日志自动重命名为当天最新版的日期然后写在一个新的日志文件中了

是自己修改的，还是SDK自带的？我0.79版还是在一个日志里。。。

**Comment by Bill-Haku** [comment]
> > 我使用的已经每天传送前一天的日志自动重命名为当天最新版的日期然后写在一个新的日志文件中了
> 
> 
> 
> 是自己修改的，还是SDK自带的？我0.79版还是在一个日志里。。。

自动在第二天就会修改

**Comment by moian98** [comment]
> > > 我使用的已经每天传送前一天的日志自动重命名为当天最新版的日期然后写在一个新的日志文件中了
> > 
> > 
> > 是自己修改的，还是SDK自带的？我0.79版还是在一个日志里。。。
> 
> 自动在第二天就会修改

？？我的为什么没有按日期分开

**Comment by traveler-vee** [comment]
@moian98

**Comment by moian98** [comment]
> @moian98

是的，windows

**Comment by moian98** [comment]
> @moian98

是的 Windows Server 2012

**Comment by traveler-vee** [comment]
windows 我要改一下才行

**Comment by moian98** [comment]
> windows 我要改一下才行

好的，辛苦了。
