### ISSUE TITLE
如何指定机器人以外的日程创建者

### ISSUE THREAD

**Issue by CodeATA** [tencent-connect/botpy#65]
我希望机器人在接收到频道成员的at命令时创建日程，并将日程的创建者设置为发送命令的频道成员。看文档应该在创建 ScheduleToCreate 对象时指定 creator 参数。我在 message.author 中获取到发送命令的成员 id，再利用 get_guild_member 获得了对应成员的  Member 对象。利用这个对象创建 ScheduleToCreate 对象之后检查发现 creator 这部分符合预期，但是调用 create_schedule 之后生成的日程里创建者永远是机器人。这种情况应该如何解决？

**Comment by traveler-vee** [comment]
我们看下这个问题
